### PR TITLE
[fixed] New props are flushed before any new transition

### LINKED ISSUE #40: Transition can fail if new props affect animation state
Ran into this writing some Tabs stuff. Essentially as you switch tabs you apply an `'active'` class that sets the display to `block` this needs to happen _before_ the `in` class is added to the element to start the animation.

As it stands transitions triggered from a prop change actually start happening _before_ the new props are flushed to the DOM. ie triggered here: https://github.com/react-bootstrap/react-overlays/blob/master/src/Transition.js#L50-L63

my thought is that we need to move these calls to componentDidUpdate. 

cc @taion

### PR DESCRIPTION
**Pull request by jquense**
fixes #40.

### CODE REVIEW

File: src/Transition.js [hunk 1]
```diff
@@ -44,31 +44,21 @@ class Transition extends React.Component {
...
+    else {
+      this._needsUpdate = true
     }
   }
 
   componentDidUpdate() {
-    if (this.props.unmountOnExit && this.state.status === EXITED) {
+    const status = this.state.status;
+
+    if (this.props.unmountOnExit && status === EXITED) {
```
Comment (taion) [inline src/Transition.js]: Do we need to `return` at the end of this and skip the bottom checks?

Comment (jquense) [inline src/Transition.js]: probably safer yeah...I'm honestly not sure though

Comment (taion) [inline src/Transition.js]: At a glance, it looks like you could at least hit `performEnter` twice, maybe.
